// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyse():Promise<any>;

export function CleanCache():Promise<void>;

export function CleanFile():Promise<void>;

export function SelectFile():Promise<string>;
