// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Analyse():Promise<Error>;

export function CleanCache():Promise<void>;

export function CleanFile():Promise<void>;

export function GetNum():Promise<number>;

export function Lottery():Promise<main.Result>;

export function SaveAs():Promise<Error>;

export function SelectFile():Promise<string>;

export function SetNum(arg1:number):Promise<void>;
