// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyse() {
  return window['go']['main']['App']['Analyse']();
}

export function CleanCache() {
  return window['go']['main']['App']['CleanCache']();
}

export function CleanFile() {
  return window['go']['main']['App']['CleanFile']();
}

export function GetNum() {
  return window['go']['main']['App']['GetNum']();
}

export function GetTotal() {
  return window['go']['main']['App']['GetTotal']();
}

export function Lottery() {
  return window['go']['main']['App']['Lottery']();
}

export function SaveAs() {
  return window['go']['main']['App']['SaveAs']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetNum(arg1) {
  return window['go']['main']['App']['SetNum'](arg1);
}
