// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyse() {
  return window['go']['main']['App']['Analyse']();
}

export function CleanCache() {
  return window['go']['main']['App']['CleanCache']();
}

export function CleanFile() {
  return window['go']['main']['App']['CleanFile']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
