// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyse():Promise<void>;

export function CleanCache():Promise<void>;

export function CleanFile():Promise<void>;

export function GetNum():Promise<number>;

export function GetTotal():Promise<number>;

export function Lottery():Promise<any>;

export function SaveAs():Promise<void>;

export function SelectFile():Promise<string>;

export function SetNum(arg1:number):Promise<void>;
